spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 1002
spring:
    profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
---
server:
  port: 1002
spring:
    profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/