spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    eureka:
     client:
      serviceUrl:
       defaultZone=http://localhost:1111/eureka/
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-XXX-test