spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
server:
  port: 1002
eureka:
   client:
     service-url: defaultZone=http://localhost:1111/eureka/
---
spring:
    profiles: test
server:
  port: 1001
eureka:
   client:
     service-url: defaultZone=http://localhost:1111/eureka/